objects/Customer_s_Order__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <label>Delivery Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery</fullName>
                    <default>true</default>
                    <label>Delivery</label>
                </value>
                <value>
                    <fullName>Pickup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer&apos;s Order</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Customer&apos;s Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer&apos;s Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_CustomerOrderHelper.cls
@IsTest
public class Test_CustomerOrderHelper {

    public static Customer_s_Order__c createOrder(String deliveryType, String status, Boolean needInsert) {
        Customer_s_Order__c order = new Customer_s_Order__c();
        order.Delivery_Type__c = deliveryType;
        order.Status__c = status;
        if (needInsert) {
            insert order;
        }
        return order;
    }

    public static List<Customer_s_Order__c> createListOfOrders(Integer numOfOrders, String deliveryType, String status, Boolean needInsert) {
        List<Customer_s_Order__c> orders = new List<Customer_s_Order__c>();
        for (Integer i = 0; i < numOfOrders; i++) {
            orders.add(createOrder(deliveryType, status, false));
        }
        if (needInsert) {
            insert orders;
        }
        return orders;
    }

}