objects/Customer_s_Order__c.object
<CustomObject>
    <fields>
        <fullName>Creation_Date__c</fullName>
        <formula>TODAY()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Creation Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <label>Delivery Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery</fullName>
                    <default>true</default>
                    <label>Delivery</label>
                </value>
                <value>
                    <fullName>Pickup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Ammount__c</fullName>
        <label>Total Ammount</label>
        <summarizedField>Order_Detail__c.Copy_Total_Price__c</summarizedField>
        <summaryForeignKey>Order_Detail__c.Customer_s_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Total_Quantity__c</fullName>
        <label>Total Quantity</label>
        <summarizedField>Order_Detail__c.Quantity__c</summarizedField>
        <summaryForeignKey>Order_Detail__c.Customer_s_Order__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Customer&apos;s Order</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Customer&apos;s Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer&apos;s Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OrderController.cls
/**
 * Created by Hanna_Yasko on 2/4/2020.
 */

public with sharing class OrderController {

    @AuraEnabled(Cacheable=true)
    public static Customer_s_Order__c[] getAllOrders(){
        Id myId = UserInfo.getUserId();
        return [SELECT Id, Name, Creation_Date__c, Total_Quantity__c,
                Total_Ammount__c,Status__c, Delivery_Type__c
        FROM Customer_s_Order__c
        WHERE OwnerId != :myId
        ORDER BY Name];
    }

    @AuraEnabled(Cacheable=true)
    public static Customer_s_Order__c[] getAllAsignedOrders(){
        Id myId = UserInfo.getUserId();
        return [SELECT Id, Name, Creation_Date__c, Total_Quantity__c,
        Total_Ammount__c, Status__c, Delivery_Type__c
        FROM Customer_s_Order__c
        WHERE OwnerId=:myId
        ORDER BY Status__c];
    }

    @AuraEnabled(Cacheable=true)
    public static String getMyId () {
        Id myId = UserInfo.getUserId();
        return [SELECT Id FROM User WHERE Id=:myId].Id;
    }

    @AuraEnabled
    public static void sendOrder(Id orderId) {
        Customer_s_Order__c customerSOrder = [SELECT Status__c FROM Customer_s_Order__c WHERE Id=:orderId];
        customerSOrder.Status__c='Sent to Customer';
        update customerSOrder;
    }

    @AuraEnabled
    public static void cancelOrder(Id orderId) {
        Customer_s_Order__c customerSOrder = [SELECT Status__c FROM Customer_s_Order__c WHERE Id=:orderId];
        customerSOrder.Status__c='Canceled';
        update customerSOrder;
    }

    @AuraEnabled
    public static void handleOrder(Id orderId) {
        Id myId = UserInfo.getUserId();
        Customer_s_Order__c customerSOrder = [SELECT OwnerId FROM Customer_s_Order__c WHERE Id=:orderId];
        customerSOrder.OwnerId = myId;
        update customerSOrder;
    }
}