objects/Customer_s_Order__c.object
<CustomObject>
    <label>Customer&apos;s Order</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Customer&apos;s Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer&apos;s Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Customer_s_Order__c</fullName>
        <label>Customer&apos;s Order</label>
        <referenceTo>Customer_s_Order__c</referenceTo>
        <relationshipLabel>Order Details</relationshipLabel>
        <relationshipName>Order_Details</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selling_Product__c</fullName>
        <label>Selling Product</label>
        <referenceTo>Selling_Product__c</referenceTo>
        <relationshipLabel>Order Details</relationshipLabel>
        <relationshipName>Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Detail</label>
    <nameField>
        <displayFormat>OD# {00000000}</displayFormat>
        <label>Order Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Selling_Product__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <formula>Quantity__c -  Ordered_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ordered_Quantity__c</fullName>
        <label>Ordered Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>quantity on the warehouse</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Selling Product</label>
    <nameField>
        <label>Selling Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OrderDetailTriggerTest.cls
@IsTest
private class OrderDetailTriggerTest {

    @TestSetup
    static void setUp(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        List<Customer_s_Order__c> orders = Test_CustomerOrderHelper.createListOfOrders(200, 'Pickup', 'In Progress', true);
        Account account = Test_AccountHelper.createAccount('testAcc', true);
        Selling_Product__c product = Test_SellingProductHelper.createProduct('testProd', 500, 50, account.Id,true);
    }

    @IsTest
    static void orderDetailCreationTest() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

        Test.startTest();
        insert getDetails();
        Test.stopTest();

        Selling_Product__c controlProduct = [SELECT Available_Quantity__c, Ordered_Quantity__c, Quantity__c
                                            FROM Selling_Product__c
                                            WHERE Name = 'testProd' LIMIT 1];
        System.assert(controlProduct.Available_Quantity__c == 100);
        System.assert(controlProduct.Ordered_Quantity__c == 400);
        System.assert(controlProduct.Quantity__c == 500);
    }

    @IsTest
    static void orderDetailCreationFailTest() {
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Boolean isFail = false;
        Selling_Product__c product = [SELECT Quantity__c FROM Selling_Product__c WHERE Name = 'testProd'LIMIT 1];
        product.Quantity__c = 1;
        update product;

        Test.startTest();
        try {
            insert getDetails();
        } catch(Exception e){
            isFail = true;
        }
        Test.stopTest();

        Selling_Product__c controlProduct = [SELECT Available_Quantity__c, Ordered_Quantity__c, Quantity__c
                                            FROM Selling_Product__c
                                            WHERE Name = 'testProd'LIMIT 1];
        System.assert(controlProduct.Available_Quantity__c == 1);
        System.assert(controlProduct.Ordered_Quantity__c == null);
        System.assert(controlProduct.Quantity__c == 1);
        System.assert(isFail);
    }

    private static List<Order_Detail__c> getDetails(){
        Selling_Product__c product = [SELECT Id FROM Selling_Product__c LIMIT 1];
        List<Order_Detail__c> details = new List<Order_Detail__c>();
        for (Customer_s_Order__c order : [SELECT Id FROM Customer_s_Order__c]) {
            details.add(Test_OrderDetailHelper.createDetail(product.Id, order.Id, 2, false));
        }
        return details;
    }
}