objects/Customer_s_Order__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <label>Delivery Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery</fullName>
                    <default>true</default>
                    <label>Delivery</label>
                </value>
                <value>
                    <fullName>Pickup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer&apos;s Order</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Customer&apos;s Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer&apos;s Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Customer_s_Order__c</fullName>
        <label>Customer&apos;s Order</label>
        <referenceTo>Customer_s_Order__c</referenceTo>
        <relationshipLabel>Order Details</relationshipLabel>
        <relationshipName>Order_Details</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selling_Product__c</fullName>
        <label>Selling Product</label>
        <referenceTo>Selling_Product__c</referenceTo>
        <relationshipLabel>Order Details</relationshipLabel>
        <relationshipName>Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Detail</label>
    <nameField>
        <displayFormat>OD# {00000000}</displayFormat>
        <label>Order Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Selling_Product__c.object
<CustomObject>
    <fields>
        <fullName>External_Id__c</fullName>
        <externalId>true</externalId>
        <label>External Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Ordered_Quantity__c</fullName>
        <label>Ordered Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>quantity on the warehouse</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Selling Product</label>
    <nameField>
        <label>Selling Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CustomersOrderHelper.cls
public with sharing class CustomersOrderHelper {

    private static final String QUEUE = 'Queue';
    private static final String DELIVERY = 'Delivery';
    private static final String PICKUP = 'Pickup';

    @Future(callout=true)
    public static void sendProductChangesToWarehouse(Set<Id> ids) {
        List<Selling_Product__c> sellingProducts = [
                SELECT Id, Name, Quantity__c, Ordered_Quantity__c, External_Id__c
                FROM Selling_Product__c
                WHERE Id IN :ids
        ];
        System.debug('RESULT ========= ' + sellingProducts);
        OrderCalloutClass.patchProductsToWarehouse(sellingProducts);
    }

    public static void updateStatusToCanceledFromInProgress(Set<Id> ids) {
        if (!ids.isEmpty()) {
            List<Selling_Product__c> sellingProducts = removeOrderedQuantityProducts(ids);
            System.debug('######## removeOrderedQuantityProducts ######### ' + sellingProducts);
            sendProductChangesToWarehouse(getProductsIds(sellingProducts));
        }
    }

    public static void updateStatusToCanceledFromSentToCustomer(Set<Id> ids) {
        if (!ids.isEmpty()) {
            List<Selling_Product__c> sellingProducts = addQuantityProducts(ids);
            System.debug('######## addQuantityProducts ######### ' + sellingProducts);
            sendProductChangesToWarehouse(getProductsIds(sellingProducts));
        }
    }

    public static void updateStatusToSentToCustomer(Set<Id> ids) {
        if (!ids.isEmpty()) {
            List<Selling_Product__c> sellingProducts = removeQuantityProducts(ids);
            System.debug('######## removeQuantityProducts ######### ' + sellingProducts);
            sendProductChangesToWarehouse(getProductsIds(sellingProducts));
        }
    }

    public static void addOrderToQueue(Set<Id> ids) {
        List<Customer_s_Order__c> customerSOrders = new List<Customer_s_Order__c>();

        if (!ids.isEmpty()) {
            customerSOrders = [
                    SELECT Id, OwnerId, Delivery_Type__c
                    FROM Customer_s_Order__c
                    WHERE Id IN :ids
            ];
            if (!customerSOrders.isEmpty()) {
                Group queueDelivery = [
                        SELECT Id, Name
                        FROM Group
                        WHERE Name = :QUEUE + ' ' + DELIVERY AND Type = :QUEUE
                ];
                Group queuePickup = [
                        SELECT Id, Name
                        FROM Group
                        WHERE Name = :QUEUE + ' ' + PICKUP AND Type = :QUEUE
                ];

                if (queuePickup != null && queueDelivery != null) {
                    for(Customer_s_Order__c customerSOrder : customerSOrders) {
                        if (customerSOrder.Delivery_Type__c.equals(DELIVERY)) {
                            customerSOrder.OwnerId = queueDelivery.Id;
                        } else if (customerSOrder.Delivery_Type__c.equals(PICKUP)) {
                            customerSOrder.OwnerId = queuePickup.Id;
                        }
                    }
                }
                update customerSOrders;
            }
        }
    }

    private static Set<Id> getProductsIds(List<Selling_Product__c> sellingProducts) {
        Set<Id> ids = new Set<Id>();
        for (Selling_Product__c sellingProduct : sellingProducts) {
            ids.add(sellingProduct.Id);
        }
        return ids;
    }

    private static List<Selling_Product__c> addQuantityProducts(Set<Id> ids) {
        List<Selling_Product__c> sellingProducts = new List<Selling_Product__c>();

        if (!ids.isEmpty()) {
            List<Order_Detail__c> orderDetails = [
                    SELECT Quantity__c, Selling_Product__r.Id, Customer_s_Order__r.Id
                    FROM Order_Detail__c
                    WHERE Customer_s_Order__r.Id IN :ids
            ];

            Map<Id, Decimal> products = new Map<Id, Decimal>();

            Set<Id> productIds = new Set<Id>();
            for (Order_Detail__c orderDetail : orderDetails) {
                productIds.add(orderDetail.Selling_Product__r.Id);
            }
            sellingProducts = [SELECT Id, Name, Quantity__c, Ordered_Quantity__c FROM Selling_Product__c WHERE Id IN :productIds];

            for (Integer i = 0; i < sellingProducts.size(); i++) {
                Decimal quantity = 0;
                for (Integer j = 0; j < orderDetails.size(); j++) {
                    if ((sellingProducts[i].Id).equals(orderDetails[j].Selling_Product__r.Id)) {
                        quantity += orderDetails[j].Quantity__c;
                    }
                }
                sellingProducts[i].Quantity__c += quantity;
            }
            update sellingProducts;
        }

        return sellingProducts;
    }

    private static List<Selling_Product__c> removeQuantityProducts(Set<Id> ids) {
        List<Selling_Product__c> sellingProducts = new List<Selling_Product__c>();

        if (!ids.isEmpty()) {
            List<Order_Detail__c> orderDetails = [
                    SELECT Quantity__c, Selling_Product__r.Id, Customer_s_Order__r.Id
                    FROM Order_Detail__c
                    WHERE Customer_s_Order__r.Id IN :ids
            ];

            Map<Id, Decimal> products = new Map<Id, Decimal>();

            Set<Id> productIds = new Set<Id>();
            for (Order_Detail__c orderDetail : orderDetails) {
                productIds.add(orderDetail.Selling_Product__r.Id);
            }
            sellingProducts = [SELECT Id, Name, Quantity__c, Ordered_Quantity__c FROM Selling_Product__c WHERE Id IN :productIds];

            for (Integer i = 0; i < sellingProducts.size(); i++) {
                Decimal quantity = 0;
                for (Integer j = 0; j < orderDetails.size(); j++) {
                    if ((sellingProducts[i].Id).equals(orderDetails[j].Selling_Product__r.Id)) {
                        quantity += orderDetails[j].Quantity__c;
                    }
                }
                sellingProducts[i].Quantity__c -= quantity;
                sellingProducts[i].Ordered_Quantity__c -= quantity;
            }
            update sellingProducts;
        }

        return sellingProducts;
    }

    private static List<Selling_Product__c> removeOrderedQuantityProducts(Set<Id> ids) {
        List<Selling_Product__c> sellingProducts = new List<Selling_Product__c>();

        if (!ids.isEmpty()) {
            List<Order_Detail__c> orderDetails = [
                    SELECT Quantity__c, Selling_Product__r.Id, Customer_s_Order__r.Id
                    FROM Order_Detail__c
                    WHERE Customer_s_Order__r.Id IN :ids
            ];
            Map<Id, Decimal> products = new Map<Id, Decimal>();

            Set<Id> productIds = new Set<Id>();
            for (Order_Detail__c orderDetail : orderDetails) {
                productIds.add(orderDetail.Selling_Product__r.Id);
            }
            sellingProducts = [SELECT Id, Name, Quantity__c, Ordered_Quantity__c FROM Selling_Product__c WHERE Id IN :productIds];

            for (Integer i = 0; i < sellingProducts.size(); i++) {
                Decimal quantity = 0;
                for (Integer j = 0; j < orderDetails.size(); j++) {
                    if ((sellingProducts[i].Id).equals(orderDetails[j].Selling_Product__r.Id)) {
                        quantity += orderDetails[j].Quantity__c;
                    }
                }
                sellingProducts[i].Ordered_Quantity__c -= quantity;
            }
            update sellingProducts;
        }
        return sellingProducts;
    }
}