objects/Customer_s_Order__c.object
<CustomObject>
    <fields>
        <fullName>Delivery_Type__c</fullName>
        <label>Delivery Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Delivery</fullName>
                    <default>true</default>
                    <label>Delivery</label>
                </value>
                <value>
                    <fullName>Pickup</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer&apos;s Order</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Customer&apos;s Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer&apos;s Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Customer_s_Order__c</fullName>
        <label>Customer&apos;s Order</label>
        <referenceTo>Customer_s_Order__c</referenceTo>
        <relationshipLabel>Order Details</relationshipLabel>
        <relationshipName>Order_Details</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selling_Product__c</fullName>
        <label>Selling Product</label>
        <referenceTo>Selling_Product__c</referenceTo>
        <relationshipLabel>Order Details</relationshipLabel>
        <relationshipName>Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Detail</label>
    <nameField>
        <displayFormat>OD# {00000000}</displayFormat>
        <label>Order Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Selling_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Selling Products</relationshipLabel>
        <relationshipName>Selling_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <formula>Quantity__c -  Ordered_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>quantity on the warehouse</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Selling Product</label>
    <nameField>
        <label>Selling Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CustomerController.cls
/**
 * Created by Hanna_Yasko on 2/3/2020.
 */

public with sharing class CustomerController {

    @AuraEnabled
    public static void saveProducts(String products, String deliveryType) {
        System.debug(products);
        Map<String, Integer> productMap = (Map<String, Integer>)
                JSON.deserialize(products, Map<String, Integer>.class);

        Customer_s_Order__c order = new Customer_s_Order__c();
        order.Delivery_Type__c = deliveryType;
        insert order;

        List<Selling_Product__c> sell_products = [
                SELECT Id
                FROM Selling_Product__c
                WHERE Id IN:productMap.keySet()
        ];

        List<Order_Detail__c> orderDetails = new List<Order_Detail__c>();

        for (Selling_Product__c product : sell_products) {
            Integer quantity = productMap.get(product.Id);
            orderDetails.add(new Order_Detail__c(
                    Selling_Product__c = product.Id,
                    Quantity__c = quantity,
                    Customer_s_Order__c = order.Id));
        }
        insert orderDetails;
    }

    @AuraEnabled(Cacheable=true)
    public static List<Selling_Product__c> searchProducts(String searchTerm, Decimal maxPrice, List<String> categories){
        return Database.query('SELECT Id, Name, Price__c, RecordType.DeveloperName, Account__r.Name FROM Selling_Product__c ' +
                'WHERE Available_Quantity__c > 0 AND Price__c <= :maxPrice AND RecordType.DeveloperName IN :categories AND Name LIKE \'%' + searchTerm + '%\'');
    }
}