objects/Customer_s_Order__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                    <default>true</default>
                    <label>In Progress</label>
                </value>
                <value>
                    <fullName>Sent to Customer</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Canceled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Customer&apos;s Order</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{0}</displayFormat>
        <label>Customer&apos;s Order Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer&apos;s Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Customer_s_Order__c</fullName>
        <label>Customer&apos;s Order</label>
        <referenceTo>Customer_s_Order__c</referenceTo>
        <relationshipLabel>Order Details</relationshipLabel>
        <relationshipName>Order_Details</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Selling_Product__c</fullName>
        <label>Selling Product</label>
        <referenceTo>Selling_Product__c</referenceTo>
        <relationshipLabel>Order Details</relationshipLabel>
        <relationshipName>Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Detail</label>
    <nameField>
        <displayFormat>OD# {00000000}</displayFormat>
        <label>Order Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Selling_Product__c.object
<CustomObject>
    <label>Selling Product</label>
    <nameField>
        <label>Selling Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/GarbageBatchTest.cls
@IsTest
private class GarbageBatchTest {

    @TestSetup
    private static void setUp(){
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
        Account account = Test_AccountHelper.createAccount('testAcc', true);
        Selling_Product__c product = Test_SellingProductHelper.createProduct('testProd', 500, 10, account.Id, true);
        List<Customer_s_Order__c> orders = Test_CustomerOrderHelper.createListOfOrders(200, 'Pickup', 'Completed', true);
        List<Order_Detail__c> details = new List<Order_Detail__c>();
        for (Customer_s_Order__c order : orders){
            details.add(Test_OrderDetailHelper.createDetail(product.Id, order.Id, 1, false));
        }
        insert details;
    }

    @IsTest
    static void testBatch() {
        List<Customer_s_Order__c> orders = [SELECT Status__c, CreatedDate FROM Customer_s_Order__c LIMIT 100];
        Integer daysToDelete = (Integer) [SELECT Days_to_Clean__c FROM Cleaning_Days__mdt LIMIT 1].Days_to_Clean__c;
        Date fakeDate = Date.today() - daysToDelete - 1;
        for (Customer_s_Order__c order : orders){
            Test.setCreatedDate(order.Id, fakeDate);
        }
        update orders;
        System.debug(orders);
        Test.startTest();
        GarbageBatch garbageBatch = new GarbageBatch();
        Database.executeBatch(garbageBatch);
        Test.stopTest();

        System.assert([SELECT Status__c, CreatedDate FROM Customer_s_Order__c].size() == 100);
    }
}