objects/Order_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Selling_Product__c</fullName>
        <label>Selling Product</label>
        <referenceTo>Selling_Product__c</referenceTo>
        <relationshipLabel>Order Details</relationshipLabel>
        <relationshipName>Order_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order Detail</label>
    <nameField>
        <displayFormat>OD# {00000000}</displayFormat>
        <label>Order Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Selling_Product__c.object
<CustomObject>
    <fields>
        <fullName>Available_Quantity__c</fullName>
        <formula>Quantity__c -  Ordered_Quantity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Available Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ordered_Quantity__c</fullName>
        <label>Ordered Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>quantity on the warehouse</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Selling Product</label>
    <nameField>
        <label>Selling Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OrderDetailHelper.cls
/**
 * Created by Hanna_Yasko on 2/10/2020.
 */

public with sharing class OrderDetailHelper {

    public static void changeAvailableQuantity(List<Order_Detail__c> newOrder){
        Set<Id> ids = new Set<Id>();
        for(Order_Detail__c order : newOrder){
            ids.add(order.Selling_Product__c);
        }

        Map<Id, Selling_Product__c> products = new Map<Id, Selling_Product__c>(
        [SELECT Name, Available_Quantity__c, Ordered_Quantity__c
        FROM Selling_Product__c
        WHERE Id IN :ids]);
        for(Order_Detail__c order : newOrder){
            if(order.Quantity__c <= products.get(order.Selling_Product__c).Available_Quantity__c){
                if (products.get(order.Selling_Product__c).Ordered_Quantity__c != null) {
                    products.get(order.Selling_Product__c).Ordered_Quantity__c += order.Quantity__c;
                } else {
                    products.get(order.Selling_Product__c).Ordered_Quantity__c = order.Quantity__c;
                }
            } else {
                throw new NotEnoughProductsException('Not enough ' + products.get(order.Selling_Product__c).Name + ' on the warehouse!');
            }
        }
        CustomersOrderHelper.sendProductChangesToWarehouse(products.keySet());
        update products.values();
    }
}