objects/Selling_Product__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Selling Products</relationshipLabel>
        <relationshipName>Selling_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <description>quantity on the warehouse</description>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Selling Product</label>
    <nameField>
        <label>Selling Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_SellingProductHelper.cls
@IsTest
public with sharing class Test_SellingProductHelper {

    public static Selling_Product__c createProduct(String name, Integer quantity,
            Double price, Id accountId, Boolean needInsert) {
        Selling_Product__c product = new Selling_Product__c();
        product.Name = name;
        product.Quantity__c = quantity;
        product.Price__c = price;
        product.Account__c = accountId;
        if (needInsert) {
            insert product;
        }
        return product;
    }

    public static List<Selling_Product__c> createListOfProducts(Integer numOfProducts,
            String nameTemplate, Integer quantity, Double price, Id accountId, Boolean needInsert) {
        List<Selling_Product__c> products = new List<Selling_Product__c>();
        for (Integer i = 0; i < numOfProducts; i++) {
            products.add(createProduct(nameTemplate + (i + 1),
                    quantity, price, accountId, false));
        }
        if (needInsert) {
            insert products;
        }
        return products;
    }
}