objects/Selling_Product__c.object
<CustomObject>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Selling Product</label>
    <nameField>
        <label>Selling Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Selling Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/FilterController.cls
/**
 * Created by Hanna_Yasko on 2/5/2020.
 */

public with sharing class FilterController {

    @AuraEnabled(Cacheable=true)
    public static List<String> searchCategories(){
        List<RecordType> types = [SELECT RecordType.DeveloperName FROM RecordType Where SobjectType = 'Selling_Product__c'];
        List<String> availableCategories = new List<String>();
        for(RecordType type : types){
            availableCategories.add(type.DeveloperName);
        }
        return availableCategories;
    }

    @AuraEnabled(Cacheable=true)
    public static Decimal searchForMaxPrice(){
        return (Decimal)[SELECT MAX(Price__c) maxPrice FROM Selling_Product__c ].get(0).get('maxPrice');
    }
}